POST http://localhost:8000/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "12345678"
}

###

POST http://localhost:8000/users/generate-token
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "12345678"
}